### ISSUE TITLE
Can't lock vehicle with L key

### ISSUE THREAD

**Issue by nutter887** [MaDHouSe79/mh-vehiclekeys#1]
Hi i got some your mh-vehiclekeys today but i have problem when i buy vehicle i try to lock my vehicle with L key but it's not work.

**Comment by MaDHouSe79** [comment]
you need mh-vehiclekeyitem for the mh-vehiclekeys script. ;) also you need to edit some scripts

**Comment by nutter887** [comment]
Oh okay  I thought mh-vehiclekeyitem it's optional lol  but it's required thank you so much MaDHouSe

**Comment by MaDHouSe79** [comment]
yeah i was forgot to add that sorry, there was optinal but that needs to be required. cause you need to edit fome script before this 2 scripts work togetter. you see all the code in mh-vehiclekeyitem what you have to do to make it work.
