### ISSUE TITLE
char stuck after trying to carjack and owned cars not working

### ISSUE THREAD

**Issue by AlexGThess** [MaDHouSe79/mh-vehiclekeys#3]
after trying to carjack vehicle, the character stuck on the move to get to the car and needs relog to be ok again.

lock/unlock owned vehicles also not working.

**Comment by MaDHouSe79** [comment]
wel this is just a version so people know how to add my mh-vehiclekeyitem to it, you can use the normal keyscript from qb-core if you don't use my vehiclekeyitem script.

**Comment by AlexGThess** [comment]
because i dont use the mh item script cause those two issues?
